spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-shell?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081

# 设置服务选择规则
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
env:
  devs
